version: "3"

services:
  nginx:
    image: nginx:stable-alpine-perl
    restart: always
    ports:
      - 80:80
    volumes:
      - ./html:/html
      - ./logs:/etc/nginx/logs
      - ./conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf