version: "3"

services:

  crawl_list:
    build:
      context: crawl_list
      dockerfile: crawl_list/Dockerfile

  crawl_tags:
    build:
      context: crawl_urllist
      dockerfile: crawl_urllist/Dockerfile

  crawl_detail:
    build:
      context: crawl_detail
      dockerfile: crawl_detail/Dockerfile

  storage_detail:
    build:
      context: storage_detail
      dockerfile: storage_detail/Dockerfile