version: "3"

services:

  crawl_list:
    build:
      context: crawl_list
      dockerfile: Dockerfile

  crawl_tags:
    build:
      context: crawl_urllist
      dockerfile: Dockerfile

  crawl_detail:
    build:
      context: crawl_detail
      dockerfile: Dockerfile

  storage_detail:
    build:
      context: storage_detail
      dockerfile: Dockerfile